services:
  nginx:
    build:
      context: ./nginx
    restart: always
    volumes:
      - static_volume:/app/static:ro  # read-only volume
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - appnet

  web:
    build:
      context: .
    restart: on-failure
    volumes:
      - static_volume:/app/static
    expose:
      - "8000"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - appnet

  redis:
    image: redis:7.4.3-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'redis-cli ping'"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - appnet

  db:
    image: postgres:16.9
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - appnet

  celery:
    build:
      context: .
    restart: unless-stopped
    command: celery -A prowlscan worker -l INFO
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - appnet

volumes:
  static_volume:
  db_data:

networks:
  appnet:
    driver: bridge
